### PR TITLE
http request fix

### PR DESCRIPTION
**Pull request by prikshittekta**

### CODE REVIEW

**Comment by ar2rsawseen** [comment]
I think same could be done also in https://github.com/Countly/countly-sdk-nodejs/blob/master/lib/countly-bulk.js too

**Comment by Code-Crash** [comment]
Hi @ar2rsawseen  and @prikshittekta, I got the same issue because of this code is not in ("countly-sdk-nodejs": "^18.8.1"),

which version does support it?

Thanks.

**Comment by ar2rsawseen** [comment]
Hello,
yes it has been added after 18.8.1, will be available soon together with new server version. Hopefully this month. We try to sync releases together :)

**Comment by Code-Crash** [comment]
@ar2rsawseen Thanks 👍

**Pull request merged**
